=== 190031241-pchaturyaakhila/epskilling/Enterprise-Programming-main/task-2_validation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Students_Info (student+)>
<!ELEMENT student (name,id,avg,dob,time,mobile,distinction)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== 190031241-pchaturyaakhila/epskilling/Enterprise-Programming-main/task-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students_Info SYSTEM "task-2_validation.dtd">
<Students_Info>
<student>
<name>Prathyusha</name>
<id>190030716</id>
<avg>98</avg>
<dob>09-09-2002</dob>
<time>13:36</time>       
<mobile>9849984900</mobile>       
<distinction>YES</distinction> 
</student>
<student>
<name>Priya</name>
<id>190030001</id>
<avg>95</avg>
<dob>06-14-2001</dob>
<time>06:15</time>        
<mobile>9345623476</mobile>            
<distinction>YES</distinction>
</student>
<student>
<name>Pranathi</name>
<id>190030002</id>
<avg>97</avg>
<dob>01-02-2002</dob>
<time>20:45</time>        
<mobile>9849984900</mobile>            
<distinction>NO</distinction>
</student>
<student>
<name>Ramya</name>
<id>190030003</id>
<avg>94</avg>
<dob>08-07-2002</dob>
<time>17:06</time>        
<mobile>9678934900</mobile>            
<distinction>YES</distinction>
</student>
<student>
<name>Harika</name>
<id>190030004</id>
<avg>90</avg>
<dob>09-21-2001</dob>
<time>19:27</time>        
<mobile>9121345667</mobile>            
<distinction>YES</distinction>
</student>
</Students_Info>
